# Generated by Django 5.1.1 on 2024-09-30 08:36

import django.contrib.auth.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('league', '0002_player_games_played_player_league_points_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='player_vp',
            field=models.PositiveIntegerField(default=0, verbose_name=django.contrib.auth.models.User),
        ),
    ]
