# Generated by Django 5.1.1 on 2024-09-30 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('league', '0003_player_player_vp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='player_vp',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
