# Generated by Django 5.1.1 on 2024-10-04 13:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('league', '0008_updatestats'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UpdateStats',
        ),
    ]
